# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
### [your code here]
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [2]:
### [your code here]
print(np.__version__)

# the configuration says how numpy was built (BLAS/LAPACK libraries it uses)
np.show_config()

2.5.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-l0z84qdl/cp314-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-l0z84qdl/cp314-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.34.0.0  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=24
    pc file directory: D:/a/numpy-release/numpy-release/.openblas
    version: 0.3.34.0.0
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-l0z84qdl/cp314-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-l0z84qdl/cp314-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas conf

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [3]:
### [your code here]
# Three ways to build a random 2x3x5 array:

# 1) random floats between 0 and 1
a = np.random.random((2, 3, 5))

# 2) same thing, older interface that takes the sizes separately
a = np.random.rand(2, 3, 5)

# 3) random integers in a range
a = np.random.randint(0, 100, size=(2, 3, 5))

# 4) values from a normal distribution (mean 0, std 1)
a = np.random.randn(2, 3, 5)

# keep the simple one for the rest of the lab
a = np.random.random((2, 3, 5))
a.shape

(2, 3, 5)


### 4. Print a.


In [4]:
### [your code here]
print(a)

[[[0.14088235 0.44563122 0.59405063 0.2224073  0.37705322]
  [0.57899038 0.99820777 0.73363504 0.22592227 0.38144089]
  [0.4594053  0.11932987 0.69017194 0.77346885 0.24754068]]

 [[0.46995931 0.95689421 0.01452376 0.57715335 0.45866568]
  [0.02560197 0.77031769 0.80650368 0.52928091 0.26554983]
  [0.16855783 0.75640269 0.59811667 0.2556939  0.11917668]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [5]:
### [your code here]
# np.ones fills the whole array with 1
b = np.ones((5, 2, 3))
b.shape

(5, 2, 3)


### 6. Print b.


In [6]:
### [your code here]
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [7]:
### [your code here]
# SIZE = how many numbers in total, no matter how they are arranged
print("a.size:", a.size, "| b.size:", b.size)
print("same size?", a.size == b.size)          # True: 2*3*5 = 5*2*3 = 30

# SHAPE = how those numbers are arranged - and here they differ
print("a.shape:", a.shape, "| b.shape:", b.shape)
print("same shape?", a.shape == b.shape)       # False

a.size: 30 | b.size: 30
same size? True
a.shape: (2, 3, 5) | b.shape: (5, 2, 3)
same shape? False



### 8. Are you able to add a and b? Why or why not?


In [8]:
### [your code here]
# No - adding needs matching shapes (or shapes numpy can broadcast).
# a is (2, 3, 5) and b is (5, 2, 3), so numpy refuses:
try:
    a + b
except ValueError as e:
    print("ValueError:", e)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [9]:
### [your code here]
# b is (5, 2, 3) and we need (2, 3, 5).
#
# transpose takes the NEW axis order written in terms of the OLD positions:
#   new axis 0  <- old axis 1  (size 2)
#   new axis 1  <- old axis 2  (size 3)
#   new axis 2  <- old axis 0  (size 5)
c = np.transpose(b, (1, 2, 0))

print("b.shape:", b.shape)
print("c.shape:", c.shape)
print("same shape as a?", c.shape == a.shape)

# Two things that look like they would work here but do not:
print()
print("b.T.shape:", b.T.shape, "<- .T reverses ALL axes, giving (3, 2, 5)")
print("b.reshape(2, 3, 5).shape:", b.reshape(2, 3, 5).shape,
      "<- right shape, wrong operation")

# reshape re-reads the same numbers in a different grouping; transpose moves
# the axes and keeps each element's identity. On this array you cannot tell
# them apart because every value is 1 - on real data they differ completely.

b.shape: (5, 2, 3)
c.shape: (2, 3, 5)
same shape as a? True

b.T.shape: (3, 2, 5) <- .T reverses ALL axes, giving (3, 2, 5)
b.reshape(2, 3, 5).shape: (2, 3, 5) <- right shape, wrong operation



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [10]:
### [your code here]
d = a + c

print("a.shape:", a.shape, " c.shape:", c.shape, " d.shape:", d.shape)
print()
print("Why it works now: addition is ELEMENT-WISE, so numpy needs the two")
print("arrays to line up position by position. a was (2,3,5) and b was")
print("(5,2,3) - same 30 numbers, but arranged so that no element of one")
print("corresponds to an element of the other. Transposing b into c put the")
print("axes in the same order, so a[i,j,k] now has a partner at c[i,j,k].")
print()
print("Note the sizes were ALWAYS equal (30 each). Equal size is not enough;")
print("it is the shape that has to match.")

a.shape: (2, 3, 5)  c.shape: (2, 3, 5)  d.shape: (2, 3, 5)

Why it works now: addition is ELEMENT-WISE, so numpy needs the two
arrays to line up position by position. a was (2,3,5) and b was
(5,2,3) - same 30 numbers, but arranged so that no element of one
corresponds to an element of the other. Transposing b into c put the
axes in the same order, so a[i,j,k] now has a partner at c[i,j,k].

Note the sizes were ALWAYS equal (30 each). Equal size is not enough;
it is the shape that has to match.



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [11]:
### [your code here]
print("a:")
print(a)
print()
print("d:")
print(d)
print()
print("d - a:")
print(d - a)

print()
print("Every element of d is exactly 1 greater than the matching element of")
print("a. That is because c is all ones - it came from b, which np.ones")
print("filled with 1, and transposing moves values around without changing")
print("them. So d = a + 1, element by element.")
print()
print("check: is (d - a) all ones?", np.allclose(d - a, 1))

# np.allclose rather than == because these are floating point numbers.
# Here the arithmetic happens to be exact, but comparing floats with ==
# is a habit worth not forming.

a:
[[[0.14088235 0.44563122 0.59405063 0.2224073  0.37705322]
  [0.57899038 0.99820777 0.73363504 0.22592227 0.38144089]
  [0.4594053  0.11932987 0.69017194 0.77346885 0.24754068]]

 [[0.46995931 0.95689421 0.01452376 0.57715335 0.45866568]
  [0.02560197 0.77031769 0.80650368 0.52928091 0.26554983]
  [0.16855783 0.75640269 0.59811667 0.2556939  0.11917668]]]

d:
[[[1.14088235 1.44563122 1.59405063 1.2224073  1.37705322]
  [1.57899038 1.99820777 1.73363504 1.22592227 1.38144089]
  [1.4594053  1.11932987 1.69017194 1.77346885 1.24754068]]

 [[1.46995931 1.95689421 1.01452376 1.57715335 1.45866568]
  [1.02560197 1.77031769 1.80650368 1.52928091 1.26554983]
  [1.16855783 1.75640269 1.59811667 1.2556939  1.11917668]]]

d - a:
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]

Every element of d is exactly 1 greater than the matching element of
a. That is because c is all ones - it came from b, which np.ones
filled with 1, a


### 12. Multiply a and c. Assign the result to e.


In [12]:
### [your code here]
e = a * c

print("e.shape:", e.shape)
print()
print("e:")
print(e)

# * is element-wise multiplication, NOT matrix multiplication.
# For matrix products numpy uses @ or np.matmul, which would fail here
# anyway because these are 3-dimensional arrays with mismatched inner
# dimensions.

e.shape: (2, 3, 5)

e:
[[[0.14088235 0.44563122 0.59405063 0.2224073  0.37705322]
  [0.57899038 0.99820777 0.73363504 0.22592227 0.38144089]
  [0.4594053  0.11932987 0.69017194 0.77346885 0.24754068]]

 [[0.46995931 0.95689421 0.01452376 0.57715335 0.45866568]
  [0.02560197 0.77031769 0.80650368 0.52928091 0.26554983]
  [0.16855783 0.75640269 0.59811667 0.2556939  0.11917668]]]




### 13. Does e equal to a? Why or why not?


In [13]:
### [your code here]
print("e equals a?")
print("  (e == a).all()      :", (e == a).all())
print("  np.array_equal(e, a):", np.array_equal(e, a))
print("  np.allclose(e, a)   :", np.allclose(e, a))

print()
print("Yes. c is entirely ones, and multiplying any number by 1 returns that")
print("same number, so a * c reproduces a exactly, element for element.")
print()
print("Contrast with question 10: ADDING ones shifted every value by 1, so")
print("d differs from a. MULTIPLYING by ones changes nothing, because 1 is")
print("the identity for multiplication while 0 is the identity for addition.")
print()
print("Note e is a NEW array, not another name for a:")
print("  e is a:", e is a)
print("  same values, separate objects in memory")

e equals a?
  (e == a).all()      : True
  np.array_equal(e, a): True
  np.allclose(e, a)   : True

Yes. c is entirely ones, and multiplying any number by 1 returns that
same number, so a * c reproduces a exactly, element for element.

Contrast with question 10: ADDING ones shifted every value by 1, so
d differs from a. MULTIPLYING by ones changes nothing, because 1 is
the identity for multiplication while 0 is the identity for addition.

Note e is a NEW array, not another name for a:
  e is a: False
  same values, separate objects in memory




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [14]:
### [your code here]
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

print("d_max :", d_max)
print("d_min :", d_min)
print("d_mean:", d_mean)

print()
print("These reduce the whole 2x3x5 array to a single number each. Passing")
print("an axis argument would instead reduce along one direction only:")
print("  d.max(axis=0).shape:", d.max(axis=0).shape)
print("  d.max(axis=2).shape:", d.max(axis=2).shape)

d_max : 1.9982077717085769
d_min : 1.0145237580786142
d_mean: 1.4586845291093142

These reduce the whole 2x3x5 array to a single number each. Passing
an axis argument would instead reduce along one direction only:
  d.max(axis=0).shape: (3, 5)
  d.max(axis=2).shape: (2, 3)



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [15]:
### [your code here]
f = np.empty((2, 3, 5))

print("f.shape:", f.shape)
print("f.dtype:", f.dtype)
print()
print("f straight from np.empty:")
print(f)

print()
print("np.empty does NOT initialise the memory - it hands back whatever")
print("happened to be at that address. The values above are therefore")
print("meaningless and will differ between runs. np.zeros would cost one")
print("extra pass to fill the array but gives something predictable.")
print()
print("It is safe here only because the next cell overwrites every element.")

f.shape: (2, 3, 5)
f.dtype: float64

f straight from np.empty:
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]

np.empty does NOT initialise the memory - it hands back whatever
happened to be at that address. The values above are therefore
meaningless and will differ between runs. np.zeros would cost one
extra pass to fill the array but gives something predictable.

It is safe here only because the next cell overwrites every element.





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [16]:
### [your code here]
# The ranges first. The strict inequalities mean these never touch the
# min, max or mean values themselves.
f[(d > d_min) & (d < d_mean)] = 25
f[(d > d_mean) & (d < d_max)] = 75

# Then the three exact values.
f[d == d_min] = 0
f[d == d_mean] = 50
f[d == d_max] = 100

print("values now present in f:", np.unique(f))
print("counts:")
for v in np.unique(f):
    print("   %3d appears %2d times" % (v, int((f == v).sum())))
print("total elements accounted for:", int(f.size))

# Two things worth knowing about this approach:
#
# d == d_mean will almost certainly match NOTHING. d_mean is an average of
# 30 floats, so it is vanishingly unlikely to equal any individual element
# exactly. The 50 label exists for completeness, not because it fires.
#
# Comparing floats with == is normally unsafe, but d_min and d_max were
# taken FROM d itself, so those two comparisons match the exact bit patterns
# that are already in the array and are reliable here.

values now present in f: [  0.  25.  75. 100.]
counts:
     0 appears  1 times
    25 appears 14 times
    75 appears 14 times
   100 appears  1 times
total elements accounted for: 30






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [17]:
### [your code here]
print("d:")
print(d)
print()
print("f:")
print(f)

print()
print("Spot check - lowest and highest values map to 0 and 100:")
print("  d_min = %.6f  ->  f = %.0f" % (d_min, f[d == d_min][0]))
print("  d_max = %.6f  ->  f = %.0f" % (d_max, f[d == d_max][0]))
print("  d_mean = %.6f (nothing equals it exactly)" % d_mean)
print()
print("Everything below the mean is 25, everything above it is 75, with the")
print("single smallest and largest elements singled out as 0 and 100. That")
print("matches the example in the question.")

d:
[[[1.14088235 1.44563122 1.59405063 1.2224073  1.37705322]
  [1.57899038 1.99820777 1.73363504 1.22592227 1.38144089]
  [1.4594053  1.11932987 1.69017194 1.77346885 1.24754068]]

 [[1.46995931 1.95689421 1.01452376 1.57715335 1.45866568]
  [1.02560197 1.77031769 1.80650368 1.52928091 1.26554983]
  [1.16855783 1.75640269 1.59811667 1.2556939  1.11917668]]]

f:
[[[ 25.  25.  75.  25.  25.]
  [ 75. 100.  75.  25.  25.]
  [ 75.  25.  75.  75.  25.]]

 [[ 75.  75.   0.  75.  25.]
  [ 25.  75.  75.  75.  25.]
  [ 25.  75.  75.  25.  25.]]]

Spot check - lowest and highest values map to 0 and 100:
  d_min = 1.014524  ->  f = 0
  d_max = 1.998208  ->  f = 100
  d_mean = 1.458685 (nothing equals it exactly)

Everything below the mean is 25, everything above it is 75, with the
single smallest and largest elements singled out as 0 and 100. That
matches the example in the question.


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [18]:
### [your code here]
# Same logic, but f_str holds strings. dtype '<U1' means unicode strings of
# length 1 - enough for a single letter.
f_str = np.empty((2, 3, 5), dtype='<U1')

f_str[(d > d_min) & (d < d_mean)] = 'B'
f_str[(d > d_mean) & (d < d_max)] = 'D'
f_str[d == d_min] = 'A'
f_str[d == d_mean] = 'C'
f_str[d == d_max] = 'E'

print(f_str)
print()
print("labels present:", np.unique(f_str))

print()
print("A=0  B=25  C=50  D=75  E=100, so the mapping is positional.")
print()
print("A one-line alternative, converting the numeric f we already built:")
mapping = {0.0: 'A', 25.0: 'B', 50.0: 'C', 75.0: 'D', 100.0: 'E'}
f_str2 = np.vectorize(mapping.get)(f)
print("matches the version above?", np.array_equal(f_str, f_str2))

print()
print("The dtype matters. np.empty((2,3,5), dtype='<U1') reserves ONE")
print("character per element - assigning 'BB' would silently truncate it to")
print("'B'. Using dtype=object instead would store real Python strings of")
print("any length, at the cost of speed and memory.")

[[['B' 'B' 'D' 'B' 'B']
  ['D' 'E' 'D' 'B' 'B']
  ['D' 'B' 'D' 'D' 'B']]

 [['D' 'D' 'A' 'D' 'B']
  ['B' 'D' 'D' 'D' 'B']
  ['B' 'D' 'D' 'B' 'B']]]

labels present: ['A' 'B' 'D' 'E']

A=0  B=25  C=50  D=75  E=100, so the mapping is positional.

A one-line alternative, converting the numeric f we already built:
matches the version above? True

The dtype matters. np.empty((2,3,5), dtype='<U1') reserves ONE
character per element - assigning 'BB' would silently truncate it to
'B'. Using dtype=object instead would store real Python strings of
any length, at the cost of speed and memory.
